### ISSUE TITLE
animation looks like it came from hell

### ISSUE THREAD

**Issue by EthanBoiLol** [Psycrow101/io_scene_bfbb_anm#2]
model: spongebob_bind.dff (battle for bikini bottom)

Anm: sb_tongue_slide_right.anm (battle for bikini bottom)

the animation appears to be deformed greatly

additional error message: "Bones Number Mismatch"

edit:

similar errors appear for sb_ball_move.anm (battle for bikini bottom)

**Comment by Psycrow101** [comment]
You're trying to bind animations to the wrong model. I think the animation `sb_tongue_slide_right.anm` is suitable for `sb_tongue.dff`. And `sb_ball_move.anm` for `sb_ball_bind.dff`.

**Bones Number Mismatch** means that the number of bones in the armature does not match the number of bones in the animation.

**Comment by EthanBoiLol** [comment]
appears to work! Thank you!
